[package]
name = "dumper"
version = "0.1.0"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>"]
edition = "2018"

[dependencies]
nglayoutng = { path = "../nglayoutng" }
app_units = "0.7"
euclid = "0.20"
clap = "2.32"
log = "0.4"
env_logger = "0.6"
